she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'), # /news/
    path('<int:pk>/', views.StoryView.as_view(), name='story'), # /news/3
    path('stories/', views.StoryListView.as_view(), name='stories'),
    path('add-story/', views.AddStoryView.as_view(), name='newStory'), # /news/add-story
    path('<int:pk>/edit/', views.StoryUpdateView.as_view(), name='editStory'), # /news/1/edit
    path('<int:pk>/delete/', views.StoryDeleteView.as_view(), name='deleteStory'),
]
 

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('news/', include('news.urls')), # /news/
    path('admin/', admin.site.urls), # /admin/
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')), #/users/login users/logout
]

she_codes_news/users/urls.py
from django.urls import path
from .views import CreateAccountView, UserAccountView

app_name = 'users'
urlpatterns = [
	path('create-account/', CreateAccountView.as_view(), name='createAccount'),
	path('<int:pk>/', UserAccountView.as_view(), name='userAccount'),
]

she_codes_news/news/models.py
from django.db import models
from django.contrib.auth import get_user_model


class NewsStory(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )
    pub_date = models.DateTimeField()
    content = models.TextField()
    image_url = models.CharField(max_length=100, null=True)

she_codes_news/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class CustomUser(AbstractUser):
    pass

    def __str__(self):
        return self.username

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsStory

# allow Django to infer all the form fields and validation from a model
class StoryForm(ModelForm):
    # nested class we want Django to infer from
    class Meta:
        model = NewsStory
        # list of fields to be included in the form
        fields = ['title','pub_date', 'content', 'image_url']
        widgets = {
        	'pub_date': forms.DateInput(format=('%m/%d/%Y'), attrs={'class':'form-control', 'placeholder':'Select a date', 'type':'date'}),
    	}

she_codes_news/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email']
    
class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email']

she_codes_news/news/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views import generic
from django.views.generic.edit import UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import NewsStory
from .forms import StoryForm


class IndexView(generic.ListView):
    template_name = 'news/index.html'

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all().order_by("-pub_date")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.all().order_by("-pub_date")[:4]
        context['all_stories'] = NewsStory.objects.all().order_by("-pub_date")
        return context

class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = 'story'

class AddStoryView(generic.CreateView):
    form_class = StoryForm
    context_object_name = 'storyForm'
    template_name = 'news/createStory.html'
    # use the name we called the path in urlpatterns to get the url path
    success_url = reverse_lazy('news:index')

    # overriding form_valid which is on generic.CreateView
    def form_valid(self, form):
        #set author to user logged in
        form.instance.author = self.request.user
        return super().form_valid(form)

class StoryUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = NewsStory
    fields = ['title', 'pub_date', 'content', 'image_url']
    template_name = 'news/editStory.html'
    success_url = reverse_lazy('news:index')

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user

class StoryDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = NewsStory
    template_name = 'news/deleteStory.html'
    success_url = reverse_lazy('news:index')

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user

class StoryListView(generic.ListView, LoginRequiredMixin, UserPassesTestMixin,):
    model = NewsStory
    template_name = 'news/stories.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_stories'] = NewsStory.objects.all().filter(author=self.request.user).order_by("-pub_date")
        return context

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user

she_codes_news/users/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views import generic
from .models import CustomUser
from .forms import CustomUserCreationForm

# Create your views here.
class CreateAccountView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/createAccount.html'

class UserAccountView(generic.DetailView):
    model = CustomUser
    template_name = 'users/account.html'
    context_object_name = 'user'

she_codes_news/news/templates/news/createStory.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="post">
{% comment %} security mechanism to prevent cheeky people trying rebuild your server (cross-site request forgery) {% endcomment %}
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="submit">
</form>

{% endblock content %}

she_codes_news/news/templates/news/deleteStory.html
{% extends "base.html" %}

{% block content %}
<h1>Delete</h1>
<form action="" method="post">
    	{% csrf_token %}
    	<p>Are you sure you want to delete {{ story.title }} </p>
    	<button type="submit">Confirm</button>
</form>

{% endblock %}

she_codes_news/news/templates/news/editStory.html
{% extends "base.html" %}

{% block content %}
<h1>Edit</h1>
<form action="" method="post">
    	{% csrf_token %}
    	{{ form.as_p }}
    	<button type="submit">Update</button>
</form>

{% endblock %}

she_codes_news/news/templates/news/index.html
    {% extends 'base.html' %}
    {% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock  %}
    {% block content %}
    <a href="{% url 'news:newStory' %}">Write New Story</a>
    <h2>Latest News</h2>

    <div id="latest-stories">
        {% if latest_stories %}
            {% for story in latest_stories %}
                {% include "./storyCard.html" with story=story position=forloop.counter %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    <div id="all-stories">
        {% if latest_stories %}
            {% for story in all_stories %}
                {% include "./storyCard.html" with story=story %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>
{% endblock  %}

she_codes_news/news/templates/news/stories.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}


    <div id="all-stories">
        {% for story in all_stories %}
        {% include "./storyCard.html" with story=story %}
            {% comment %} <p>{{ story.title }}</p> {% endcomment %}
        {% endfor %}
    </div>
    
{% endblock %}

she_codes_news/news/templates/news/story.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}">
{% endblock %}

{% block content %}

<div id="story-wrapper">
    <h2>{{ story.title }}</h2>
    <h4>{{ story.author }}</h4>
    <div id="story-content">
        {% if story.image_url %}
            <img src={{ story.image_url }}>
        {% else %}
            <img src="{% static '/news/images/placeholder-5.jpg' %}">
        {% endif %}
        {{ story.content|linebreaks }}
    </div>
    {% if user == story.author %}
        <div >
            <a class="story-links" href="{% url 'news:editStory' story.id %}">Edit</a>
            <a class="story-links" href="{% url 'news:deleteStory' story.id %}">Delete</a>    
        </div>
    {% endif %}
</div>
{% endblock %}

she_codes_news/news/templates/news/storyCard.html
<div class="story-card" id="story-card-{{ position }}">
    <a href="{% url 'news:story' story.id %}">
        {% if position < 3 %}
            <img src="../static/news/images/placeholder-{{ position }}.jpg">
        {% else %}
            <img src={{ story.image_url }}>
        {% endif %}
        <div class="story-card-text">
            <h3>{{ story.title }}</h3>
            <h4>{{ story.author }}</h4>
            <h4>{{ story.pub_date }}</h4>

            {% if user == story.author %}
                <div >
                    <a class="story-links" href="{% url 'news:editStory' story.id %}">Edit</a>
                    <a class="story-links" href="{% url 'news:deleteStory' story.id %}">Delete</a>    
                </div>
            {% endif %}
        </div>
    </a>
</div>

she_codes_news/templates/base.html
{% load static %}
<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>She Codes News</title>
        <meta name="description" content="">
        <meta name="author" content="Shauna">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        {% block stylesheets %}{% endblock  %}
    </head>

    <body>
        <header>
            <div id="header-text">
                <a id="header-link" href="{% url 'news:index' %}">
                    <h1>She {Codes} News</h1>
                </a>
            </div>
            <!-- include nav here -->
            {% include './nav.html' %}
        </header>

        <!-- content blocks here -->
        {% block content %}{% endblock  %}
    </body>
</html>

she_codes_news/templates/nav.html
<nav>
    <a href="{% url 'news:index' %}">Home</a>
    {% if request.user.is_authenticated %}
        <a href="{% url 'users:userAccount' user.id %}">{{ request.user.username }}</a>
        <a href="{% url 'logout' %}">Logout</a>
    {% else %}
        <a href="{% url 'login' %}">Login</a>
        <a href="{% url 'users:createAccount' %}">Sign up</a>
    {% endif %}
</nav>

she_codes_news/users/templates/users/account.html
{% extends 'base.html' %}

{% block content %}
    {% if request.user == user %}
        <h2>My Account</h2>
        <p>Username: {{ user.username }}</p>
        <p>Email: {{ user.email }}</p>
        <a class="story-links" style="text-decoration:underline" href={% url 'news:stories' %}>View my stories</a>
    {% endif%}
{% endblock %}

she_codes_news/users/templates/users/createAccount.html
{% extends 'base.html' %}

{% block content %}
<h2>Create Account</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create Account</button>
</form>

{% endblock content %}